### ISSUE TITLE
seems nothing output after running test

### ISSUE THREAD

**Issue by leiwen83** [colorjam/PAMS#3]
Hi,

I try to reproduce your result by following commands:

python main.py --scale 4 --k_bits 8  --refine ./pretrained/8bit_edsr_x4.pt --save_results  --data_test Set5+Set14+B100+Urban100   --save edsr_x4/8bit/ --dir_data ../DIV2K --test_only  --model EDSR
Load model from ./pretrained/8bit_edsr_x4.pt
edsr_x4/8bit/ start!

Evaluation:
0it [00:00, ?it/s]
[Set5 x4] PSNR: nan  (Best: nan @epoch 1)
WARNING:root:NaN or Inf found in input tensor.
0it [00:00, ?it/s]
[Set14 x4] PSNR: nan  (Best: nan @epoch 1)
WARNING:root:NaN or Inf found in input tensor.
0it [00:00, ?it/s]
[B100 x4] PSNR: nan  (Best: nan @epoch 1)
WARNING:root:NaN or Inf found in input tensor.
0it [00:00, ?it/s]
[Urban100 x4] PSNR: nan  (Best: nan @epoch 1)
WARNING:root:NaN or Inf found in input tensor.
Total: 1.12s

But there is nothing in edsr_x4/8bit/, am I missing anything else?

Thx,
Lei

**Comment by colorjam** [comment]
@leiwen83 hi, did you download the trained model from [GoogleDrive](https://drive.google.com/open?id=14p3ZBs8VQdHkMWBa5kv_qN7b0w2qJq6c), and save it in `pretrained`?

**Comment by leiwen83** [comment]
Hi @colorjam ,

I already download the pretained model. But seems also get some other problem.
```
python3 main.py --scale 4  --k_bits 8 --model EDSR --pre_train ./pretained/edsr_baseline_x4.pt --patch_size 192 --data_test Set14 --save edsr_x4/8bit/   --dir_data /data/mnt/DIV2K/ --print_every 10
Traceback (most recent call last):
  File "main.py", line 253, in <module>
    main()
  File "main.py", line 215, in main
    loader = data.Data(args)
  File "/data/dev/quant/PAMS/data/__init__.py", line 32, in __init__
    pin_memory=True
  File "/data/dev/quant/PAMS/data/dataloader.py", line 152, in __init__
    *args, **kwargs, num_workers=cfg.n_threads
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 176, in __init__
    sampler = RandomSampler(dataset)
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/sampler.py", line 66, in __init__
    "value, but got num_samples={}".format(self.num_samples))
ValueError: num_samples should be a positive integer value, but got num_samples=0
```

The /data/mnt/DIV2K/ shows as below
```
DIV2K_test_LR_bicubic  DIV2K_test_LR_unknown  DIV2K_train_HR  DIV2K_train_LR_bicubic  DIV2K_train_LR_unknown
```

**Comment by colorjam** [comment]
@leiwen83 Hi, did you download the [benchmark](https://cv.snu.ac.kr/research/EDSR/benchmark.tar)? We use the benchmark datasets to test the model.

**Comment by SumanDeedwaniya** [comment]
Hi @colorjam ,

I am facing the same issue while running the code.

(python3.6_env) suman@ant2pc:~/work/PAMS/PAMS$ python main.py --scale 4 --k_bits 8 --pre_train ./pretrained/edsr_baseline_x4.pt --save_results --data_test Set5 --save ../edsr_x4/8bit/ --dir_data ./data/benchmark/Set5/ --test_only --refine ./pretrained/8bit_edsr_x4.pt --model EDSR
Load model from ./pretrained/8bit_edsr_x4.pt
../edsr_x4/8bit/ start!

Evaluation:
0it [00:00, ?it/s]
[Set5 x4] PSNR: nan  (Best: nan @epoch 1)
WARNING:root:NaN or Inf found in input tensor.
Total: 0.25s

../edsr_x4/8bit/ done

I have downloaded the pretrained models from googledrive and stored at ./pretrained path.
Also benchmark data i have downloaded and stored at ./data/benchmark path.
Can you help what might be the issue here.
Attached are the screenshots for your reference.
![issue_3](https://user-images.githubusercontent.com/15530162/107372369-58967600-6b0b-11eb-8d89-5ea4c3665059.png)
![issue_2](https://user-images.githubusercontent.com/15530162/107372374-5a603980-6b0b-11eb-94dd-bef0cff324a0.png)
![issue_1](https://user-images.githubusercontent.com/15530162/107372379-5af8d000-6b0b-11eb-964d-ad7a2f6b2db6.png)

**Comment by colorjam** [comment]
@SumanDeedwaniya Hi, just set `--dir_data ./data`

**Comment by SumanDeedwaniya** [comment]
> @SumanDeedwaniya Hi, just set `--dir_data ./data`

Thanks @colorjam ...It worked
